### ISSUE TITLE
Documentation / Example of how to use?

### ISSUE THREAD

**Issue by idangozlan** [rochejul/sequelize-mocking#25]
It's really not clear how to use that module, but since it's maintained, I wonder if there's any chance to get example of how to use? (readme example is not working, due to imports of `../../lib/database`, etc)

Thanks

**Comment by rochejul** [comment]
Hi

It hardly depends how you use sequelize in your project, that's why I do not show the "database.js" content, because I don't want to influence your implementation

However, if you want some working examples, I suggest you go to the examples folder: https://github.com/rochejul/sequelize-mocking/tree/master/examples

The "debug" folder is used to check an issue and illustrate the resolution (or not)

The others are examples how to use sequelize-mocking through jasmine, mocha and tape

Regards

**Comment by rochejul** [comment]
No feedbacks, I close this issue

Many thanks
